config/routes.rb
Pam::Application.routes.draw do
  resources :archivos
  
  devise_for :users

    
  devise_scope :user do
    get 'confirmar', to: 'devise/confirmations#new', as: :confirmar
    get 'recuperar', to: 'devise/passwords#new', as: :recuperar
    get 'registrate', to: 'devise/registrations#new', as: :registrate
    get 'entrar', to: 'devise/sessions#new', as: :entrar
    get 'salir', to: 'devise/sessions#destroy', as: :salir
  end

	resources :cargas, controller: 'uploads' do 
		member do 
			get 'procesar', :as => 'procesar'
		end
	end

	resources :proyects, :shallow => :true do
	resources :movements
	resources :activities
	end
	
	root :to => "archivos#index"

	match '/actividades' => 'activities#activities', as: 'actividades'
	match '/movimientos' => 'movements#movements', as: 'movimientos'
	match '/dashboard' => 'landing#index', as: 'dashboard'
	match '/global_activities' => "landing#activities"
	match '/global_movements' => "landing#movements"
	
end

app/models/movement.rb
class Movement < ActiveRecord::Base
  belongs_to :proyect

  attr_accessible :ammount, :proyect_id, :rendido_beneficiario, :rendido_innova, :numero_informe, :fecha_informe, :aprobado_beneficiario, :aprobado_innova
end

app/controllers/movements_controller.rb
class MovementsController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /movements
  # GET /movements.json
  def index
    @movements = Movement.all
    @project = Proyect.find(params[:proyect_id])
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @movements }
    end
  end

  # GET /movements/1
  # GET /movements/1.json
  def show
    @project = Project.find(params[:proyect_id])
    @movement = @project.movements.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @movement }
    end
  end

  # GET /movements/new
  # GET /movements/new.json
  def new
    @project = Proyect.find(params[:proyect_id])
    @movement = @project.movements.new

    respond_to do |format|
      format.js
      format.html # new.html.erb
      format.json { render json: @movement }
    end
  end

  # GET /movements/1/edit
  def edit
    @project = Project.find(params[:proyect_id])
    @movement = @project.movements.find(params[:id])
  end

  # POST /movements
  # POST /movements.json
  def create
    @project = Proyect.find(params[:proyect_id])
    @movement = @project.movements.new(params[:movement])

    respond_to do |format|
      if @movement.save
        format.html { redirect_to  proyect_path(@project), notice: 'Movement was successfully created.' }
        format.json { render json: @movement, status: :created, location: @movement }
      else
        format.html { render action: "new" }
        format.json { render json: @movement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /movements/1
  # PUT /movements/1.json
  def update
    @project = Project.find(params[:proyect_id])
    @movement = @project.movements.find(params[:id])

    respond_to do |format|
      if @movement.update_attributes(params[:movement])
        format.html { redirect_to  proyect_path(@project), notice: 'Movement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @movement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movements/1
  # DELETE /movements/1.json
  def destroy
    @project = Project.find(params[:proyect_id])
    @movement = @project.movements.find(params[:id])
    @movement.destroy

    respond_to do |format|
      format.html { redirect_to proyect_movements_url }
      format.json { head :no_content }
    end
  end

  def movements
    @movements = Movement.all
  end
end

app/helpers/movements_helper.rb
module MovementsHelper
end

app/views/movements/_form.html.haml
= simple_form_for([@project,@movement]) do |f|
  .modal-body
    = f.error_notification
    .row
      .col-md-6
        =f.input :numero_informe, input_html: {class: 'form-control'},wrapper_html: {class: 'form-group'}, label: false, placeholder: 'Ingresa el número de informe'
        =f.input :rendido_beneficiario, input_html: {class: 'form-control'},wrapper_html: {class: 'form-group'}, label: false, placeholder: '$ Rendido por beneficiario'
        =f.input :aprobado_beneficiario, input_html: {class: 'form-control'},wrapper_html: {class: 'form-group'}, label: false, placeholder: '$ Aprobado beneficiario'
      .col-md-6
        =f.input :fecha_informe, input_html: {class: 'form-control'},wrapper_html: {class: 'form-group'}, label: false, placeholder: 'Fecha del informe'
        =f.input :rendido_innova, input_html: {class: 'form-control'},wrapper_html: {class: 'form-group'}, label: false, placeholder: '$ Rendido por innova'
        =f.input :aprobado_innova, input_html: {class: 'form-control'},wrapper_html: {class: 'form-group'}, label: false, placeholder: '$ Aprobado innova'
  .modal-footer
    %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Cerrar
    = f.button :submit, "Guardar movimiento", class: 'btn btn-primary'

app/views/movements/edit.html.haml
%h1 Editing movement

= render 'form'

= link_to 'Show', @movement
\|
= link_to 'Back', movements_path

app/views/movements/index.html.haml
=render('layouts/header')
.container
  .row
    .col-md-12
      .page-header
        .row
          .col-md-10
            %h1 Movimientos
          .col-md-2
            =link_to 'Agregar Movimento', new_proyect_movement_path, remote: true, class: 'btn btn-primary boton-side pull-irght'

      %table.table-condensed{'width' => '100%' }
        %tr
          %th Número de informe
          %th Fecha de informe
          %th Rendido por beneficiario
          %th Rendido por innova
          %th Aprobado beneficiario
          %th Aprobado innova
          


        - @movements.each do |movement|
          %tr
            %td= movement.numero_informe
            %td= movement.fecha_informe
            %td= movement.rendido_beneficiario
            %td= movement.rendido_innova
            %td= movement.aprobado_beneficiario
            %td= movement.aprobado_innova
            / %td= link_to 'Show', movement
            / %td= link_to 'Edit', edit_movement_path(movement)
            / %td= link_to 'Destroy', movement, :method => :delete, :data => { :confirm => 'Are you sure?' }

=render 'layouts/modal'

app/views/movements/movements.html.haml
=render('layouts/header')
.container
  .row
    =render('layouts/menu')
    .col-md-9
      .page-header
        .row
          .col-md-10
            %h1 Movimientos

      %table.table-condensed{'width' => '100%' }
        %tr
          %th Proyecto
          %th Monto Total
          
        - @movements.each do |movement|
          %tr
            %td= movement.ammount

app/views/movements/new.html.haml
=render('layouts/header')

.container
  .row
    =render('layouts/menu')

    .col-md-9
      .page-header
        .row
          .col-md-10
            %h1 
              =@project.name
              =" : Agregar movimiento" 
              
              =link_to "Volver atras", '', class: 'btn pull-right'
          .col-md-2

      = render 'form'

app/views/movements/new.js.erb
var title       =   '.modal-title';
var loader      =   '.ajax-loader';
var dataRemote  =   'a[data-remote=true]';
var modal       =   '#agregarModal';
var content			= 	'#contenedorMovimiento'

$(title).html("Agregar Movimiento");
$(content).html("<%= j render 'form' %>");

$(modal).modal();

app/views/movements/show.html.haml
%p#notice= notice

%p
  %b Ammount:
  = @movement.ammount
%p
  %b Proyect:
  = @movement.proyect_id

= link_to 'Edit', edit_movement_path(@movement)
\|
= link_to 'Back', movements_path