config/routes.rb
Pam::Application.routes.draw do
  resources :archivos
  
  devise_for :users

    
  devise_scope :user do
    get 'confirmar', to: 'devise/confirmations#new', as: :confirmar
    get 'recuperar', to: 'devise/passwords#new', as: :recuperar
    get 'registrate', to: 'devise/registrations#new', as: :registrate
    get 'entrar', to: 'devise/sessions#new', as: :entrar
    get 'salir', to: 'devise/sessions#destroy', as: :salir
  end

	resources :cargas, controller: 'uploads' do 
		member do 
			get 'procesar', :as => 'procesar'
		end
	end

	resources :proyects, :shallow => :true do
	resources :movements
	resources :activities
	end
	
	root :to => "archivos#index"

	match '/actividades' => 'activities#activities', as: 'actividades'
	match '/movimientos' => 'movements#movements', as: 'movimientos'
	match '/dashboard' => 'landing#index', as: 'dashboard'
	match '/global_activities' => "landing#activities"
	match '/global_movements' => "landing#movements"
	
end

app/models/proyect.rb
class Proyect < ActiveRecord::Base
  extend FriendlyId

  has_many :movements, :dependent => :destroy
  has_many :activities, :dependent => :destroy
  
  attr_accessible :name, :country, :generation, :ycode, :submitted, :readyforjudging, :code,
  					:selected, :formalized, :et, :arrivalstage, :website, :angellist, :pitch, :incorporated,
  					:demoday, :roundtable, :fulltpeople, :startupage, :capitalraisedbefore, :mentorab, :reapplaying,
  					:hearaboutsup, :startdate, :finishdate, :statusnow, :capitalraisedmusta, :datemusta, :capitalraisedmustb, 
  					:datemustb, :industry, :exitstage, :nextprogram, :incorpchile, :dateic, :incorpabroad, :dateia, :pivoted, :pnewname,
  					:finish, :ynrank

  friendly_id :name
end

app/controllers/proyects_controller.rb
class ProyectsController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /proyects
  # GET /proyects.json
  def index
    @proyects = Proyect.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @proyects }
    end
  end

  # GET /proyects/1
  # GET /proyects/1.json
  def show
    @proyect = Proyect.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @proyect }
    end
  end

  # GET /proyects/new
  # GET /proyects/new.json
  def new
    @proyect = Proyect.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @proyect }
    end
  end

  # GET /proyects/1/edit
  def edit
    @proyect = Proyect.find(params[:id])
  end

  # POST /proyects
  # POST /proyects.json
  def create
    @proyect = Proyect.new(params[:proyect])

    respond_to do |format|
      if @proyect.save
        format.html { redirect_to @proyect, notice: 'Proyect was successfully created.' }
        format.json { render json: @proyect, status: :created, location: @proyect }
      else
        format.html { render action: "new" }
        format.json { render json: @proyect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /proyects/1
  # PUT /proyects/1.json
  def update
    @proyect = Proyect.find(params[:id])

    respond_to do |format|
      if @proyect.update_attributes(params[:proyect])
        format.html { redirect_to @proyect, notice: 'Proyect was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @proyect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proyects/1
  # DELETE /proyects/1.json
  def destroy
    @proyect = Proyect.find(params[:id])
    @proyect.destroy

    respond_to do |format|
      format.html { redirect_to proyects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/proyects_helper.rb
module ProyectsHelper

	def movimientos(project)
		movimientos = project.movements
		datos = Hash.new

		datos[:rendido_beneficiario] = 0
		datos[:rendido_innova] = 0
		datos[:aprobado_beneficiario] = 0
		datos[:aprobado_innova] = 0

		movimientos.each do |movimiento|

			datos[:rendido_beneficiario] += movimiento.rendido_beneficiario unless movimiento.rendido_beneficiario.nil?
			datos[:rendido_innova] += movimiento.rendido_innova unless movimiento.rendido_innova.nil?
			datos[:aprobado_beneficiario] += movimiento.aprobado_beneficiario unless movimiento.aprobado_beneficiario.nil?
			datos[:aprobado_innova] += movimiento.aprobado_innova unless movimiento.aprobado_innova.nil?
		end
	
		return datos
	end

end

app/views/proyects/_form.html.haml
= simple_form_for(@proyect) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :country

  .form-actions
    = f.button :submit

app/views/proyects/_information.html.haml
.row
	.col-md-12
		%h2=@proyect.name
		%p
			.row
				.col-md-3
					%b Pais proyecto: 
					-if @proyect.country.nil?
						="Pais"
					-else
						=@proyect.country
				.col-md-3
					%b Generacion: 
					-if @proyect.generation.nil?
						="Generation"
					-else
						=@proyect.generation
				
				.col-md-3
					%b Industria proyecto:
					-if @proyect.industry.nil?
						="Industry"
					-else
						=@proyect.industry
				.col-md-3
					%b Ejecutivo técnico
					-if @proyect.et.nil?
						="Ejecutivo"
					-else
						=@proyect.et
			%hr
			.row
				.col-md-6
					%b Codigo Younoodle:

					-if @proyect.ycode.nil?
						="YCODE"
					-else
						=@proyect.ycode
					
				.col-md-6
					%b Codigo SGP
					-if @proyect.code.nil?
						=" CODE "
					-else
						=@proyect.code

		%hr
		%h4 PITCH
		%p
			-if @proyect.pitch.nil?
				=" Pitch no disponible"
			-else 
				=@proyect.pitch
		%hr
		%p
			%h4 DETALLES
			.row
				.col-md-4
					%b Status: 
					-if @proyect.statusnow.nil?
						=" Sin status"
					-else
						=@proyect.statusnow
				
				.col-md-4
					%b Fecha inicio: 
					-if @proyect.finishdate.nil?
						="Desconocido"
					-else
						=@proyect.finishdate

				.col-md-4
					%b Fecha termino: 
					-if @proyect.startdate.nil?
						="Desconocido"
					-else
						=@proyect.startdate
			%hr
			.row	
				.col-md-4
					%b Website:
					-if @proyect.website.nil?
						=" Website"
					-else
						=@proyect.website
				
				.col-md-4
					%b Angellist URL:
					-if @proyect.website.nil?
						=" Angellist url"
					-else
						=@proyect.angellist
		
				.col-md-4
					%b Younoodle Rank:
					-if @proyect.ynrank.nil?
						=" Rank"
					-else
						=@proyect.ynrank
			%hr
			.row
				.col-md-4
					%b Submitted:
					-if @proyect.submitted?
						=" Si"
					-else
						=" No"
				.col-md-4
					%b Ready for judging
					-if @proyect.readyforjudging?
						=" Si"
					-else
						=" No"
				.col-md-4
					%b Selected
					-if @proyect.selected?
						=" Si"
					-else
						=" No"
			%hr
			.row
				.col-md-4
					%b Formalized
					-if @proyect.formalized?
						=" Si"
					-else
						=" No"

				.col-md-4
					%b Arrival Stage
					-if @proyect.arrivalstage.nil?
						=" ArrivalStage"
					-else
						=@proyect.arrivalstage

				.col-md-4
					%b Re-applaying
					=@proyect.reapplaying
			%hr
			.row
				.col-md-4
					%b Demoday
					-if @proyect.demoday?
						=" Si Participo"
					-else
						=" No Participo"	
				.col-md-4
					%b Roundtable
					-if @proyect.roundtable?
						=" Si Participo"
					-else
						=" No Participo"
				.col-md-4
					%b Mentor
					-if @proyect.mentorab.nil?
						=" Mentor"
					-else
						=@proyect.mentorab
			%hr
			.row
				.col-md-6
					%b Startup Age
					-if @proyect.startupage.nil?
						="startupage"
					-else
						=@proyect.startupage
				.col-md-6
					%b Incorporated
					-if @proyect.incorporated?
						=" Si"
					-else
						=" No"
			%hr
			.row
				.col-md-6
					%b Incorporated in Chile
					-if @proyect.incorpchile?
						="Si"
					-else
						="No"
				.col-md-6
					%b Date incorporated
					=@proyect.dateic
			%hr
			.row
				.col-md-6
					%b Incorporated abroad
					=@proyect.incorpabroad
				.col-md-6
					%b Date incorporated abroad
					=@proyect.dateia
			%hr
			.row
				.col-md-4
					%b Full t people
					=@proyect.fulltpeople
				.col-md-4
					%b Exit stage
					=@proyect.exitstage
				.col-md-4
					%b Next Program
					=@proyect.nextprogram
			%hr
			.row
				.col-md-4
					%b Pivot
					=@proyect.pivoted
				.col-md-4
					%b Pivot name
					=@proyect.pnewname

				.col-md-4
					%b Finish
					=@proyect.finish

			%hr
			.row
				.col-md-12
					%b Hear about SUP
					=@proyect.hearaboutsup

app/views/proyects/_vacio.html.haml
%br
%br
%br
.jumbotron
	.container
		%h1 No existen datos
		%p
			Aún no se han cargado datos en este item

app/views/proyects/edit.html.haml
=render('layouts/header')
.container
  %h3 Editing proyect

  = render 'form'

app/views/proyects/index.html.haml
=render('layouts/header')

.container
  .row
    .col-md-12
      .page-header
        .row
          .col-md-7
            %h1 Proyectos
          .col-md-3
            =link_to 'Carga Masiva', new_proyect_path, class: 'btn btn-primary boton-side pull-right'
          .col-md-2
            =link_to 'Nuevo Proyecto', new_proyect_path, class: 'btn btn-primary boton-side'
      
      %table.table-condensed{'width' => '100%' }
        %thead
          %tr
            %th Proyecto
            %th Pais
            %th Raise
            %th Industria
            %th Monto Total        
        %tbody
          -@proyects.each do |p|
            %tr
              %td=link_to p.name, proyect_path(p)
              %td=p.country
              %td
              %td=p.industry

    

app/views/proyects/new.html.haml
=render('layouts/header')
.page-header
  %h1 Proyectos
.container
	.row
		=render('layouts/menu')

app/views/proyects/show.html.haml
=render('layouts/header')

.container
  .row


    .col-md-4
      .col-md-12
        %h4 MOVIMIENTOS
        .panel.panel-default
          .panel-body
            %p
              %h4.centrar TOTAL DE MOVIMIENTOS
              %p
                %b
                  %h2.centrar=link_to @proyect.movements.count, proyect_movements_path(@proyect)

          %table.table
            %tbody
              -@datos = movimientos(@proyect)
              %tr
                %td $ RENDIDO BENEFICIARIO
                %td=link_to @datos[:rendido_beneficiario], proyect_movements_path(@proyect)
              %tr
                %td $ RENDIDO INNOVA
                %td=link_to @datos[:rendido_innova], proyect_movements_path(@proyect)
              %tr
                %td $ APROBADO
                %td=link_to @datos[:aprobado_beneficiario], proyect_movements_path(@proyect)
              %tr
                %td $ APROBADO INNOVA
                %td=link_to @datos[:aprobado_innova], proyect_movements_path(@proyect)
          .panel-body
            =link_to new_proyect_movement_path(@proyect), remote: true, class: 'btn btn-primary btn-block' do 
              Agregar Movimiento
              %i.glyphicon.glyphicon-usd

      .col-md-12
        %h4 ACTIVIDADES
        .panel.panel-default
          .panel-body
            %p
              %h4.centrar PROXIMA REUNION

          %table.table
            %tbody
              %tr
                %td $ RENDIDO
                %td 
              %tr
                %td $ APROBADO
                %td
              %tr
                %td $ APROBADO INNOVA
                %td
          .panel-body
            =link_to new_proyect_activity_path(@proyect), remote: true, class: "btn btn-primary btn-block" do
              Agregar Actividades
              %i.glyphicon.glyphicon-calendar

      .col-md-12
        %h4 CAPITAL LEVANTADO
        .panel.panel-default
          .panel-body

    .col-md-8
      %h4 DETALLES DEL PROYECTO
      .panel.panel-default
        .panel-body
          =render 'information'
 

=render 'layouts/modal'