config/routes.rb
Pam::Application.routes.draw do
  resources :archivos
  
  devise_for :users

    
  devise_scope :user do
    get 'confirmar', to: 'devise/confirmations#new', as: :confirmar
    get 'recuperar', to: 'devise/passwords#new', as: :recuperar
    get 'registrate', to: 'devise/registrations#new', as: :registrate
    get 'entrar', to: 'devise/sessions#new', as: :entrar
    get 'salir', to: 'devise/sessions#destroy', as: :salir
  end

	resources :cargas, controller: 'uploads' do 
		member do 
			get 'procesar', :as => 'procesar'
		end
	end

	resources :proyects, :shallow => :true do
	resources :movements
	resources :activities
	end
	
	root :to => "archivos#index"

	match '/actividades' => 'activities#activities', as: 'actividades'
	match '/movimientos' => 'movements#movements', as: 'movimientos'
	match '/dashboard' => 'landing#index', as: 'dashboard'
	match '/global_activities' => "landing#activities"
	match '/global_movements' => "landing#movements"
	
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  attr_accessible :attached
  has_attached_file :attached
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @uploads = Upload.all
  end

  def show
  end

  def new
    @upload = Upload.new
    respond_to do |format|
      format.html
      format.json { render json: @upload }
    end
  end

  def edit
  end

  def create
    @upload = Upload.new(params[:upload])

    respond_to do |format|
      if @upload.save
        format.html { redirect_to cargas_path, notice: 'El archivo fue cargado.'}
        format.json { render json: cargas_path, status: :created, location: @upload }
      else
        format.html { render action: "new" }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
  end

  def destroy
  end

  def procesar
    @upload = Upload.find(params[:id])
    @datos = Roo::Excelx.new(root_url  + @upload.attached.url) 
    @datos.default_sheet = @datos.sheets[0]
    headers = Hash.new
    @datos.row(1).each_with_index { |header, i| headers[header] = i }

    ((@datos.first_row + 1 )..@datos.last_row).each do |row|
      name = @datos.row(row)[headers['Project Name']]
      country = @datos.row(row)[headers['Country']]

      generation = @datos.row(row)[headers['Country']]
      ycode = @datos.row(row)[headers['Country']]
      submitted = @datos.row(row)[headers['Country']]
      readyforjudging = @datos.row(row)[headers['Country']]
      code = @datos.row(row)[headers['Country']]
      selected = @datos.row(row)[headers['Country']]
      formalized = @datos.row(row)[headers['Country']]
      et = @datos.row(row)[headers['Country']]
      arrivalstage = @datos.row(row)[headers['Country']]
      website = @datos.row(row)[headers['Country']]
      angellist = @datos.row(row)[headers['Country']]
      pitch = @datos.row(row)[headers['Country']]
      incorporated = @datos.row(row)[headers['Country']]
      demoday = @datos.row(row)[headers['Country']]
      roundtable = @datos.row(row)[headers['Country']]
      fulltpeople = @datos.row(row)[headers['Country']]
      startupage = @datos.row(row)[headers['Country']]
      capitalraisedbefore = @datos.row(row)[headers['Country']]
      mentorab = @datos.row(row)[headers['Country']]
      reapplaying = @datos.row(row)[headers['Country']]
      hearaboutsup = @datos.row(row)[headers['Country']]
      startdate = @datos.row(row)[headers['Country']]
      finishdate = @datos.row(row)[headers['Country']]
      statusnow = @datos.row(row)[headers['Country']]
      capitalraisedmusta = @datos.row(row)[headers['Country']]
      datemusta = @datos.row(row)[headers['Country']]
      capitalraisedmustb = @datos.row(row)[headers['Country']]
      datemustb = @datos.row(row)[headers['Country']]
      exitstage = @datos.row(row)[headers['Country']]
      nextprogram = @datos.row(row)[headers['Country']]
      incorpchile = @datos.row(row)[headers['Country']]
      dateic = @datos.row(row)[headers['Country']]
      incorpabroad = @datos.row(row)[headers['Country']]
      dateia = @datos.row(row)[headers['Country']]
      pivoted = @datos.row(row)[headers['Country']]
      pnewname = @datos.row(row)[headers['Country']]

    @projects = Proyect.all
  end
end
  

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/uploads/_form.html.haml
%hr
=simple_form_for @upload, :url => cargas_path do |f|
	=f.input :attached, label: false
	%hr
	=f.button :submit, 'Migrar', class: 'btn btn-primary btn-block'

app/views/uploads/index.html.haml
=render('layouts/header')
.container
	.page-header
		%h2 Carga de archivos
		%p
			Recuerda que esta carga de archivo sólo la debe hacer Konrad o Nelson por ahora. Ya que hay que validar la planilla
	.row
		.span7.hero-unit
			-if @uploads.count > 0
				%table.table.table-bordered
					%tr	
						%th Fecha Carga
						%th URL
						%th Cargar
					-@uploads.each do |upload|
						%tr
							%td=upload.created_at
							%td=link_to "Descargar", upload.attached.url
							%td=link_to 'Cargar Datos', procesar_carga_path(upload), class:'btn btn-primary btn-block'
			-else
				%p No hay cargas
		
		.span2.hero-unit
			=link_to 'Nueva Carga', new_carga_path, class: 'btn btn-primary btn-block'

app/views/uploads/new.html.haml
=render('layouts/header')
.container
	.page-header
		%h2 Nueva Carga
	.row
		.span4
			
		.span3.hero-unit
			%h4
				Selecciona archivo
			=render 'form'
		.span3

app/views/uploads/procesar.html.haml
=debug @projects

app/views/uploads/show.html.haml
%h1 Uploads#show
%p Find me in app/views/uploads/show.html.haml