config/routes.rb
Pam::Application.routes.draw do
  resources :archivos
  
  devise_for :users

    
  devise_scope :user do
    get 'confirmar', to: 'devise/confirmations#new', as: :confirmar
    get 'recuperar', to: 'devise/passwords#new', as: :recuperar
    get 'registrate', to: 'devise/registrations#new', as: :registrate
    get 'entrar', to: 'devise/sessions#new', as: :entrar
    get 'salir', to: 'devise/sessions#destroy', as: :salir
  end

	resources :cargas, controller: 'uploads' do 
		member do 
			get 'procesar', :as => 'procesar'
		end
	end

	resources :proyects, :shallow => :true do
	resources :movements
	resources :activities
	end
	
	root :to => "archivos#index"

	match '/actividades' => 'activities#activities', as: 'actividades'
	match '/movimientos' => 'movements#movements', as: 'movimientos'
	match '/dashboard' => 'landing#index', as: 'dashboard'
	match '/global_activities' => "landing#activities"
	match '/global_movements' => "landing#movements"
	
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :proyect

  attr_accessible :description, :proyect_id, :title, :date_activity, :etapa_actual, :need_comunications, :experience, :notes, :nuevos_usuarios, :nuevos_clientes,
  								:ventas_mensuales_actuales, :venden_en_mas_paises, :nuevos_empleados_chilenos, :nuevos_empleados_extranjeros, :nuevos_outsourcing_chilenos, :nuevos_outsourcing_extranjeros, :fecha_proxima_reunion
  #esto deberian ser texto: mentorship, rva, operations

  #tabla de raice_capita|amount, date, whow, country| hitos|descripcion, fecha_comprometida, fecha_logrado, boolean logrado {si, no}| goals|lo mismo que la otra, porcentaje logrado|
end

#date_activity:string etapa_actual:string{ just on idea/concept, prototyping, beta, scaling operation, scaling sales}, need_comunications:text experience:text 
#notes:text nuevos_usuarios:integer nuevos_clientes:integer ventas_mensuales_actuales:integer venden_en_mas_paises:string nuevos_empleados_chilenos:integer nuevos_empleados_extranjeros:integer 
#nuevos_outsourcing_chilenos:integer nuevos_outsourcing_extranjeros:integer fecha_proxima_reunion:string

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /activities
  # GET /activities.json
  def index
    @project = Proyect.find(params[:proyect_id])
    @activities = @project.activities

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @activities }
    end
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    @project = Proyect.find(params[:proyect_id])
    @activity = @project.activities.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/new
  # GET /activities/new.json
  def new
    @project = Proyect.find(params[:proyect_id])
    @activity = @project.activities.new

    respond_to do |format|
      format.js
      format.html # new.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/1/edit
  def edit
    @project = Proyect.find(params[:proyect_id])
    @activity = @project.activities.find(params[:id])
  end

  # POST /activities
  # POST /activities.json
  def create
    @project = Proyect.find(params[:proyect_id])
    @activity = @project.activities.new(params[:activity])

    respond_to do |format|
      if @activity.save
        format.html { redirect_to proyect_path(@project), notice: 'Activity was successfully created.' }
        format.json { render json: proyect_activities_url, status: :created, location: @activity }
      else
        format.html { render action: "new" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /activities/1
  # PUT /activities/1.json
  def update
    @project = Proyect.find(params[:proyect_id])
    @activity = @project.activities.find(params[:id])

    respond_to do |format|
      if @activity.update_attributes(params[:activity])
        format.html { redirect_to proyect_path(@project), notice: 'Activity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @project = Proyect.find(params[:proyect_id])
    @activity = @project.activities.find(params[:id])
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to proyect_activities_url }
      format.json { head :no_content }
    end
  end

  def activities
    @activities = Activity.all
  end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.haml
= simple_form_for ([@project, @activity]) do |f|
  .modal-body
    = f.error_notification
    .row
      .col-md-12
        =f.input :title, input_html: {class: 'form-control'},wrapper_html: {class: 'form-group'}, label: false, placeholder: 'Titulo para la actividad'
      
      .col-md-4
        =f.input :nuevos_usuarios, input_html: {class: 'form-control'},wrapper_html: {class: 'form-group'}, label: false, placeholder: 'Nuevos Usuarios'
      .col-md-4
        =f.input :date_activity, input_html: {class: 'form-control'},wrapper_html: {class: 'form-group'}, label: false, placeholder: 'Fecha reunión'
      .col-md-4
        =f.input :fecha_proxima_reunion, input_html: {class: 'form-control'},wrapper_html: {class: 'form-group'}, label: false, placeholder: 'Próxima reunión'


      .col-md-4
        =f.input :nuevos_clientes, input_html: {class: 'form-control'},wrapper_html: {class: 'form-group'}, label: false, placeholder: 'N° nuevos clientes'
      .col-md-4
        =f.input :ventas_mensuales_actuales, input_html: {class: 'form-control'},wrapper_html: {class: 'form-group'}, label: false, placeholder: 'Venta mensual actual'
      .col-md-4
        =f.input :venden_en_mas_paises, input_html: {class: 'form-control'},wrapper_html: {class: 'form-group'}, label: false, placeholder: 'N° paises venden'
      .col-md-4
        =f.input :etapa_actual, input_html: {class: 'form-control'},wrapper_html: {class: 'form-group'}, label: false, placeholder: 'Etapa actual'


      .col-md-4
        =f.input :nuevos_empleados_chilenos, input_html: {class: 'form-control'},wrapper_html: {class: 'form-group'}, label: false, placeholder: 'N° emp. chilenos'
      .col-md-4
        =f.input :nuevos_empleados_extranjeros, input_html: {class: 'form-control'},wrapper_html: {class: 'form-group'}, label: false, placeholder: 'N° emp. extranjeros'
      .col-md-6
        =f.input :nuevos_outsourcing_chilenos, input_html: {class: 'form-control'},wrapper_html: {class: 'form-group'}, label: false, placeholder: 'N° new outsourcing CL'
      .col-md-6
        =f.input :etapa_actual, input_html: {class: 'form-control'},wrapper_html: {class: 'form-group'}, label: false, placeholder: 'N° new outsourcing extranjero'

      .col-md-4
        =f.input :need_comunications, input_html: {class: 'form-control'},wrapper_html: {class: 'form-group'}, label: false, placeholder: 'Necesita comunicación'
      .col-md-4
        =f.input :experience, input_html: {class: 'form-control'},wrapper_html: {class: 'form-group'}, label: false, placeholder: 'Experiencia'
      .col-md-4
        =f.input :notes, input_html: {class: 'form-control'},wrapper_html: {class: 'form-group'}, label: false, placeholder: 'Notas'

  .modal-footer
    %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Cerrar
    = f.button :submit, "Guardar Actividad", class: 'btn btn-primary'

app/views/activities/edit.html.haml
%h1 Editing activity

= render 'form'

= link_to 'Show', @activity
\|
= link_to 'Back', activities_path

app/views/activities/index.html.haml
=render('layouts/header')

  %table.table.table-bordered
    %tr
      %th Title
      %th Description
      %th
      %th
      %th

    - @activities.each do |activity|
      %tr
        %td= activity.title
        %td= activity.description
        %td= link_to 'Show', activity
        %td= link_to 'Edit', edit_activity_path(activity)
        %td= link_to 'Destroy', activity, :method => :delete, :data => { :confirm => 'Are you sure?' }

  %br

  = link_to 'New Activity', new_proyect_activity_path

app/views/activities/new.html.haml
=render('layouts/header')

.container
  .row
    =render('layouts/menu')

    .col-md-9
      .page-header
        .row
          .col-md-10
            %h1 
              =@project.name
              =" : Agregar Actividad" 
              
              =link_to "Volver atras", '', class: 'btn pull-right'
          .col-md-2

      = render 'form'

app/views/activities/new.js.erb
var title       =   '.modal-title';
var loader      =   '.ajax-loader';
var dataRemote  =   'a[data-remote=true]';
var modal       =   '#agregarModal';
var content			= 	'#contenedorMovimiento'

$(title).html("Agregar Actividad");
$(content).html("<%= j render 'form' %>");
$(modal).modal();

app/views/activities/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @activity.title
%p
  %b Description:
  = @activity.description
%p
  %b Proyect:
  = @activity.proyect_id

= link_to 'Edit', edit_activity_path(@activity)
\|
= link_to 'Back', activities_path